service:
    docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t deemocat/alpine-opencv-java:v4.2.0 .
  - docker push deemocat/alpine-opencv-java:v4.2.0